# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.box = "ubuntu/xenial64"
  config.vm.provider :virtualbox do |vb|
    vb.memory = 2048
    vb.cpus = 1
  config.ssh.insert_key = true
  config.vm.provision "shell", inline: <<-SHELL
    apt-get update
    apt-get upgrade -y
    apt-get install python-minimal -y
    sudo sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config
    sudo service ssh restart
    echo -e "password\npassword" | sudo passwd ubuntu
  SHELL
  end

  # Docker Master 1.
  config.vm.define "docker7" do |srv|
    srv.vm.hostname = "docker-master-7"
    srv.vm.network :private_network, ip: "192.168.60.16"
  end
   # Docker Master 2. 
   config.vm.define "docker8" do |srv|
     srv.vm.hostname = "docker-master-8"
     srv.vm.network :private_network, ip: "192.168.60.17"
   end
   # Docker Master 3. 
   config.vm.define "docker9" do |srv|
     srv.vm.hostname = "docker-master-9"
     srv.vm.network :private_network, ip: "192.168.60.18"
   end
end

