# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
VAGRANTFILE_API_VERSION = "2"

vm_name1= "utest1"
vm_name2= "utest2"

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"
  config.vm.provider :virtualbox do |vb|
    vb.memory = 2048
    vb.cpus = 1
  config.vm.provision "shell", inline: <<-SHELL
    apt-get update
    apt-get upgrade -y
    apt-get install iperf -y
  SHELL
end

# Docker Master 1.
config.vm.define vm_name1 do |srv|
  srv.vm.hostname = vm_name1
  srv.vm.network 'private_network', virtualbox__intnet: true, ip: '192.168.100.10'
  
  config.vm.provider :virtualbox do |vb|
    vb.customize ['modifyvm', :id, '--nic2', 'intnet',
    '--intnet2', 'vEOS-intnet1']
    vb.gui = true
    end
end
 # Docker Master 2. 
 config.vm.define vm_name2 do |srv|
   srv.vm.hostname = vm_name2
   srv.vm.network 'private_network', virtualbox__intnet: true, ip: '192.168.100.11'

   config.vm.provider :virtualbox do |vb|
    vb.customize ['modifyvm', :id, '--nic2', 'intnet',
    '--intnet2', 'vEOS-intnet2']
    vb.gui = true
    end
end

end
