# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.

vm_name = "cvx"

Vagrant.configure("2") do |config|

    # The most common configuration options are documented and commented below.
    # For a complete reference, please see the online documentation at
    # https://docs.vagrantup.com.
  
    # Every Vagrant development environment requires a box. You can search for
    # boxes at https://vagrantcloud.com/search.
  
    config.vm.box = "cvx"
    config.vm.hostname = vm_name
    # Create Ethernet1
    config.vm.network 'private_network', virtualbox__intnet: true,
    ip: '169.254.2.11', auto_config: false
    # Create Ethernet2
    config.vm.network 'private_network', virtualbox__intnet: true,
    ip: '169.254.2.11', auto_config: false
    
    config.vm.provider :virtualbox do |vb| 
    # Networking:
    # nic1 is always Management1 which is set to dhcp in the basebox.
    
    # Patch Ethernet1 to a particular internal network
    vb.customize ['modifyvm', :id, '--nic2', 'intnet',
    '--intnet2', 'cvx-intnet1']
    # Patch Ethernet2 to a particular internal network
    vb.customize ['modifyvm', :id, '--nic3', 'intnet',
    '--intnet3', 'cvx-intnet2']
    # Display the VirtualBox GUI when booting the machine
    vb.gui = true
  
    end
end
